name: Kernel Staging

on:
  workflow_dispatch:
    inputs:
      toolchain:
          description: 'Write toolchain name gcc/clang'
          required: true
      branch:
          description: 'Write kernel branch r-oss/wip'
          required: true
env:
  BRANCH: ${{ github.event.inputs.branch }}
  COMP: ${{ github.event.inputs.toolchain }}
  TELEGRAM_TOKEN: ${{ secrets.TG_TOKEN }}
  TELEGRAM_CHAT: ${{ secrets.TG_CHAT }}
  VER: ${{ secrets.K_NAME }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/neutron-projects/docker-image:arch-neutron
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Start building kernel
        run: |
             git config --global --add safe.directory /__w/build/build
             git clone https://github.com/Dwyor-tmx/sm6225_xiaomi_fog -b gcc2 kernel-wip
             cp -af build.sh kernel-wip/ && cd kernel-wip && chmod +x build.sh
             ./build.sh
